### ISSUE TITLE
Showing the same user the same imagery sets more than once

### ISSUE THREAD

**Issue by bgirardot** [mapswipe/mapswipe#22] opened 2018-07-21 07:21 UTC
I routinely get the same sets of imagery more than once.

I am only doing the mapping online method.

As you can see in the examples below, the only difference is that one was shown to me at 9:04 and 5 minutes later, probably 2 sets of images later, there is the exact same image. I was taking screenshots for a tutorial so luckily can prove it and not just "I swear I have seen that before... maybe not"

You will also note that they are both at the same % mapped in the set and I can confirm, it was exact the same set after this image.

![img_0647-combined](https://user-images.githubusercontent.com/265831/43033293-18e03772-8cc8-11e8-844c-acb1e2c243be.jpg)

**Comment by PimDeWitte** [comment] 2018-07-29 04:53
I noticed an index was placed wrong in firebase and fixed the index. I suspect this may have to do with this issue but I can not confirm until it is verified. 

If it does not fix the issue at hand, it may have to do with an updated caching behavior on Firebase's end, for which a front end fix will have to be issued. This should not be crazy complicated.

Let me know if it's fixed. If not, I will plan some time to make a front end fix.

**Comment by bgirardot** [comment] 2018-07-29 12:06
Thank you very much Pim, I will do my best to test!

**Comment by bgirardot** [comment] 2018-07-30 05:34
So after more testing trying to see if it mattered if I was doing complete session or map further options, it does not seem to matter one way or another, I get duplicate sets using either method.

![img_07127](https://user-images.githubusercontent.com/265831/43379078-ebb32688-93ca-11e8-8b55-e78fcceffa5e.jpg)

**Comment by ahstro** [comment] 2019-05-26 14:29
This is happening to me as well, both with "Map further" and between sessions. How are non-tapped tiles handled? I could see myself making the error of making non-tapped "unseen" and therefore make the set "unseen"

**Comment by laurentS** [comment] 2019-05-26 18:53
#49 is a duplicate of this one, but relates to the updated code, we'll post updates there.

**Comment by laurentS** [comment] 2019-12-13 15:06
This should not be an issue any more, with the fix for #49. If not, please reopen.

**Closed by laurentS** 2019-12-13 15:06 UTC
