### ISSUE TITLE
Last screen only shows 3 cells

### ISSUE THREAD

**Issue by tobylyte** [mapswipe/mapswipe#145] opened 2019-10-22 03:32 UTC
**Describe the bug**
In the latest version (2.0.1) once you've swiped all the way to the right, the last screen often only has 3 tiles instead of the 6 I'd expect. 

**App version**
2.0.1

**To Reproduce**
1. Select one of the projects
2. Swipe left repeatedly (19 times) marking up cells as normal until you reach the last screen showing satellite imagery
3. I now observe satellite imagery in the 3 left hand cells and not in the right hand ones.

It doesn't happen every time. There's not an obvious pattern. 

It happens nearly every time with. 
"Disaster preparedness Indonesia (3) - British red cross" and "Economic development Philippines (1) - Humanitarian Open Street Map team"

I am not able to recreate it with "Health Emergency Chad (1) - Medecins Sans Frontiers

**Screenshots**
![Screenshot_2019-10-19-09-35-17-097_org missingmaps mapswipe](https://user-images.githubusercontent.com/3061722/67257085-05b22e80-f482-11e9-9617-08d0da0321ac.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 8
 - OS: Miui 10.3.5 stable
Android 8 PKQ1.180729.001

**Additional context**
I've tried the "Bugs? Clear project data" button and it doesn't make any difference.

**Comment by laurentS** [comment] 2019-10-22 06:57
Hi @tobylyte, thanks for reporting this. It's actually not a bug, but the result of a bugfix, see #123. Let me know if it makes sense.
In any case, you thought it was a problem, so we can probably do a better job of either explaining, or showing those cases in a different way.

**Comment by edent** [comment] 2019-10-23 03:40
I think it might be useful to have a "No tile" image there. 

I came here to report the same bug because I thought the tiles simply hadn't loaded.

**Comment by laurentS** [comment] 2020-01-15 10:59
@Hagellach37 this could also be fixed by adjusting the group size during generation to ensure they're always multiples of 2

**Comment by Hagellach37** [comment] 2020-01-15 12:32
yes, 
I think this would be a fix. So let's close this issue here and open another one for the back end.

**Closed by Hagellach37** 2020-01-15 12:32 UTC
