### ISSUE TITLE
Text about marking all tiles RED is cut off on smaller phones

### ISSUE THREAD

**Issue by habi** [mapswipe/mapswipe#233] opened 2020-06-11 08:52 UTC
**Describe the bug**
The text explaining about swiping down is cut off on smaller phone screens and cannot be read fully.

**App version**
2.0.4

**To Reproduce**
1. Start a project
2. Slighly swipe down

**Screenshots**
![Screenshot 2020-06-10 at 11 30 45](https://user-images.githubusercontent.com/1651235/84365377-a4d29480-abd1-11ea-98e1-22d9c7e907ed.png)

**Smartphone (please complete the following information):**
 - Device: iPhone SE (original)
 - OS: iOs 13.5.5

**Comment by laurentS** [comment] 2020-06-11 18:07
This looks like a duplicate of #154 , though you seem to have the issue without increasing the system font size. In any case, I'll push it back to the top of the pile, I think it'll get dragged into the #182 updates anyway :)
Thanks for the report!

**Comment by habi** [comment] 2020-06-11 19:31
> This looks like a duplicate of #154 <https://github.com/mapswipe/mapswipe/issues/154> , though you seem to have the issue without increasing the system font size.

Sorry, I didn’t search the issues thoroughly enough.
I have *not* increased the system font size, I just have a small phone :)
I guess this issue could be closed as as duplicate then.

> In any case, I'll push it back to the top of the pile, I think it'll get dragged into the #182 <https://github.com/mapswipe/mapswipe/issues/182> updates anyway :)

Thanks.
I’m looking forward to help with translating MapSwipe, BTW!

**Comment by laurentS** [comment] 2020-06-11 20:14
If you're keen on translating, [this](https://www.transifex.com/mapswipe/mapswipe-app) might help ;)

I'll close this now.

**Closed by laurentS** 2020-06-11 20:14 UTC

**Comment by habi** [comment] 2020-06-13 20:02
I asked to 'join the team', is there a manual process of accepting translators?

**Comment by laurentS** [comment] 2020-06-14 12:20
Yes, indeed. I just approved your request.

**Comment by habi** [comment] 2020-06-23 13:18
German is now fully translated :)
